package org.example.spu;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/department") 
public class DepartmentController {
  @Autowired // This means to get the bean called departmentRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private DepartmentRepository departmentRepository;

  public DepartmentController(DepartmentRepository repository){
    departmentRepository = repository;
  }

  @PostMapping(path="/add")
  public @ResponseBody Department addNewDepartment(@RequestParam String name, @RequestParam(required = false) Long parentId) {
    Department n = new Department();
    n.setName(name);
    n.setParentId(parentId);
    return departmentRepository.save(n);
  }

  @PutMapping(path="/edit")
  public @ResponseBody Department EditDepartment(@RequestParam Long id, @RequestParam String name, @RequestParam(required = false) Long parentId) {
    Department n = new Department();
    n.setId(id);
    n.setName(name);
    n.setParentId(parentId);
    return departmentRepository.save(n);
  }

  @DeleteMapping(path="/delete")
  public @ResponseBody void RemoveDepartment(@RequestParam Long id){
    Department d = new Department();
    d.setId(id);
    departmentRepository.delete(d);
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Department> getAllDepartments() {
    return departmentRepository.findAll();
  }
}