package org.example.spu;

import java.util.Date;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller 
@RequestMapping(path="/employer") 
public class EmployerController {
  @Autowired // This means to get the bean called departmentRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private EmployerRepository employerRepository;
  private DepartmentRepository departmentRepository;

  public EmployerController(EmployerRepository employerRepository, DepartmentRepository departmentRepository){
    this.employerRepository = employerRepository;
    this.departmentRepository = departmentRepository;
  }

  @PostMapping(path="/add") 
  public @ResponseBody String addNewEmployer(@RequestParam String name, @RequestParam Date birthDate, @RequestParam String gender, @RequestParam Long departmentId) {
    Department d = null;
    if (departmentId != null){
        Optional<Department> o = departmentRepository.findById(departmentId);
        if (o.isPresent()){
            d = o.get();
        }
    }
    Gender g = null;
    if (gender != null) {
        g = Gender.valueOf(gender);
    }
    Employer e = new Employer(null, name, birthDate, g, d);
    Employer oe = employerRepository.save(e);
    return String.valueOf(oe.getId());
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Employer> getAllEmployers() {
    return employerRepository.findAll();
  }
}